<?php session_start(); $city = trim($_GET['city'] ?? ''); ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>PG Listings | VizagPG Finder</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/style.css"></head>
<body class="pglife-body">
<nav class="site-nav"><div class="container nav-inner"><a class="brand-logo" href="index.php"><span class="brand-mark">⌂</span><span class="brand-pg">PG</span><span class="brand-life">Life</span></a><div class="nav-right"><span id="userGreeting" class="user-greeting"></span><a class="nav-link-btn" href="profile.php">👤 Profile</a><button class="nav-link-btn" data-bs-toggle="modal" data-bs-target="#authModal">↪ <span id="authNavText">Login</span></button></div></div></nav>
<header class="listing-hero"><div class="container"><div class="breadcrumb-lite"><a href="index.php">Home</a> / PG Listings</div><div class="city-switch"><a href="listings.php?city=Delhi">Delhi</a><a href="listings.php?city=Mumbai">Mumbai</a><a href="listings.php?city=Bengaluru">Bengaluru</a><a href="listings.php?city=Hyderabad">Hyderabad</a><a href="listings.php?city=Vizag">Vizag</a></div><h1>PGs in <span id="cityTitle">Visakhapatnam</span></h1><p>Find a comfortable PG that fits your location, budget and lifestyle.</p></div></header>
<main class="container listing-wrap">
  <div id="reactFeature" class="react-shortlist"></div><div class="listing-toolbar"><button class="filter-open" data-bs-toggle="modal" data-bs-target="#filterModal">☷ <span>Filters</span></button><div><strong id="resultCount">0</strong> properties</div><select id="sortSelect" class="sort-select"><option value="default">Sort by: Recommended</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="rating">Rating</option></select></div>
  <div id="activeFilters" class="active-filters"></div>
  <div id="propertyGrid" class="row g-4"></div><div id="emptyState" class="empty-state d-none">No properties match your filters.</div>
</main>
<footer class="site-footer"><div class="container footer-cities"><a href="listings.php?city=Delhi">PG in Delhi</a><a href="listings.php?city=Mumbai">PG in Mumbai</a><a href="listings.php?city=Bengaluru">PG in Bengaluru</a><a href="listings.php?city=Hyderabad">PG in Hyderabad</a><a href="listings.php?city=Visakhapatnam">PG in Vizag</a></div><div class="container footer-copy">© 2026 VizagPG Finder</div></footer>

<div class="modal fade" id="filterModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content filter-modal"><div class="modal-header"><h3 class="modal-title">Filters</h3><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><h5>Gender</h5><div class="choice-row"><button class="choice active" data-gender="">⚭ <span>No Filter</span></button><button class="choice" data-gender="Co-living">⚭ <span>Unisex</span></button><button class="choice" data-gender="Boys">♂ <span>Male</span></button><button class="choice" data-gender="Girls">♀ <span>Female</span></button></div><hr><h5>Budget</h5><div class="budget-row"><button class="choice budget-choice active" data-budget="">Any</button><button class="choice budget-choice" data-budget="0-7000">Up to ₹7,000</button><button class="choice budget-choice" data-budget="7001-10000">₹7,001–₹10,000</button><button class="choice budget-choice" data-budget="10001-15000">₹10,001–₹15,000</button></div></div><div class="modal-footer"><button id="applyFilters" class="filter-ok">Okay</button></div></div></div></div>
<div class="modal fade" id="authModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content auth-card"><div class="modal-header"><h5 class="modal-title">Login / Sign up</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><ul class="nav nav-tabs mb-3"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#loginTab">Login</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#signupTab">Sign up</button></li></ul><div class="tab-content"><div class="tab-pane fade show active" id="loginTab"><form id="loginForm"><input class="form-control mb-2" name="email" type="email" placeholder="Email" required><input class="form-control mb-3" name="password" type="password" placeholder="Password" required><button class="primary-btn w-100">Login</button></form></div><div class="tab-pane fade" id="signupTab"><form id="signupForm"><input class="form-control mb-2" name="name" placeholder="Full name" required><input class="form-control mb-2" name="email" type="email" placeholder="Email" required><input class="form-control mb-2" name="phone" placeholder="Phone"><input class="form-control mb-3" name="password" type="password" placeholder="Password (6+ characters)" required><button class="primary-btn w-100">Create account</button></form></div></div><div id="authMessage" class="small mt-3"></div></div></div></div>
<script src="https://unpkg.com/react@18/umd/react.development.js"></script><script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script><script src="https://unpkg.com/@babel/standalone/babel.min.js"></script><script>window.INIT_CITY=<?php echo json_encode($city); ?>;</script><script src="assets/react-component.jsx" type="text/babel"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/listings.js?v=20260926"></script></body></html>
